# Generated by Django 4.0.3 on 2022-06-30 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaymentManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='numero_cartao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='referencia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
