# Generated by Django 4.0.3 on 2022-06-29 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminManagement', '0003_alter_lugar_contratoid_alter_lugar_reservaid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zona',
            name='tipo_de_zona',
            field=models.CharField(blank=True, db_column='Tipo de Zona', max_length=255, null=True),
        ),
    ]
